pull_request_rules:
  - name: automatic merge for master branch when CI passes and 1 reviews
    conditions:
      - "#approved-reviews-by>=1"
      # checks < ======
      - check-success=golangci-lint
      - check-success=Build
      - check-success=unit tests
      # checks ====== >
      - base=main
    actions:
      merge:
        method: merge

  - name: automatic merge for Dependabot pull requests
    conditions:
      - author=dependabot[bot]
            # checks < ======
      - check-success=golangci-lint
      - check-success=Build
      - check-success=unit tests
      # checks ====== >
    actions:
      merge:
        method: merge
