# This file contains all available configuration options
# with their default values.

# options for analysis running
run:
  tests: true

issues:
  exclude-rules:
    - linters:
        - funlen
      # Disable 'funlen' linter for test functions.
      # It's common for table-driven tests to be more than 60 characters long
      source: "^func Test"

linters:
  enable-all: true
  disable:
    - gomnd
    - gocognit
    - goerr113
    - gofumpt
    - gci
    - nlreturn
    - testpackage
    - gochecknoglobals
    - gochecknoinits
    - godot
    - exhaustivestruct
    # https://github.com/golangci/golangci-lint/issues/541
    - interfacer
