# .goreleaser.yml proposed options for Romie
builds:
  - env:
      - CGO_ENABLED=0
  # You can have multiple builds defined as a yaml list
  - main: main.go
    id: "romie"
    dir: .
    binary: romie

    goos:
      - linux
      - darwin
      - windows
      - freebsd
      - openbsd
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{ .CommitDate }} -X main.builtBy=goreleaser
