name: build

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'
  pull_request:

jobs:
  Building:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-latest, macos-latest]
    steps:
      - name: Checkout out source code
        uses: actions/checkout@v2.3.3
        with:
          fetch-depth: 0
          
      - name: Set up Go environment
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.15
          
      - name: Cache Go modules
        uses: actions/cache@v2.1.2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
            
      - name: make setup
        run: |
          make setup
          
      - name: make lint
        run: |
          make lint
          
      - name: make build
        run: |
          make build
          
      - name: make test
        run: |
          make test
          
      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: romie ${{ matrix.os }}
          path: ${{ github.workspace }}
          
      - name: make run
        run: |
          make run
