name: builder

on:
  push:
    tags:
      - v*
    branches:
      - master
      - main
  pull_request:
    branches:
      - "*"

jobs:
  builder:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout out source code
        uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Set up Go environment
        uses: actions/setup-go@v3.2.0
        with:
          go-version-file: './go.mod'
      - run: go version

      - name: Go imports
        uses: Jerome1337/goimports-action@v1.0.3

      - name: Go fmt
        uses: Jerome1337/gofmt-action@v1.0.5
        with:
          gofmt-flags: '-l -d'

      - name: Go mod tidy
        uses: Jerome1337/gomod-action@v1.0.0

      - name: Set GCC
        run: |
          sudo apt-get --allow-releaseinfo-change update
          sudo apt-get install -y gcc

      - name: Go build
        run: go build -o romie
