name: 'Publish docs'
on:
  push:
    tags:
      - v*
    branches:
      - master
      - main

jobs:
  deploy:
    name: Update the website
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - run: pip install mkdocs-material

      - run: |
          mkdocs gh-deploy --force
