name: test

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'
  pull_request:

jobs:
  test:
    name: "unit tests"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout out source code
        uses: actions/checkout@master

      - name: Install GCC
        run: |
          sudo apt-get --allow-releaseinfo-change update
          sudo apt-get install -y gcc

      - name: Set up Go environment
        uses: actions/setup-go@v3.2.0
        with:
          go-version-file: './go.mod'
      - run: go version

      - name: Go Test
        run: go test -failfast -race -coverpkg=./... -covermode=atomic -coverprofile=coverage.txt ./... -run . -timeout 5m
